<?php
/**
 * Template for Mage_Page_Block_Html
 */
?>
<?php
	 $helper = Mage::helper('ves_tempcp/data');
	 $config = $helper->get();
	 $cookies = Mage::getModel('core/cookie')->get();
	 $skin_default =  ( !isset($cookies['skin']) || (isset($cookies['skin']) && empty($cookies['skin']))) ? $config["skin"] : $cookies["skin"];
	 $bgpattern = ( !isset($cookies['bgpattern']) || (isset($cookies['bgpattern']) && empty($cookies['bgpattern']))) ? $config["backgroundpattern"] : $cookies["bgpattern"];
	 $layout = ( !isset($cookies['layout']) || (isset($cookies['layout']) && empty($cookies['layout']))) ? $config["layout"] : $cookies["layout"];
	 $responsive = ( !isset($cookies['responsive']) || ( isset($cookies['responsive']) && empty($cookies['responsive']))) ? $config['responsive'] : $cookies['responsive'];
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>">
<head>

<?php echo $this->getChildHtml('head') ?>
<?php if( $config['enable_customfont'] ): ?>
	<?php echo $this->getLayout()->createBlock("ves_tempcp/googlefont")->setConfig( $config )->toHtml( );?>
<?php else : ?>
	<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl(); ?>css/font.css" media="all" />
<?php endif; ?>

</head>
<body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass() ." ".$bgpattern.' '.$layout.'"':'class="'.$bgpattern.' '.$layout.'"' ?> id="<?php echo $bgpattern;?>">
<?php echo $this->getChildHtml('after_body_start') ?>
<div id="ves-wrapper" class="wrapper">
    <?php echo $this->getChildHtml('global_notices') ?>
    <div id="ves-page" class="page">
        <?php echo $this->getChildHtml('header') ?>
		
		<?php if( $slider = $this->getChildHtml('slider') ): ?>
		<!-- slideshow module //-->
		<div class="wrap-slideshow">
			<div id="ves-slider-top" class="slider-top promotetop">
					<div class="bg-1">
						<?php echo $slider; ?>			
					</div>
			</div>
		</div>	
		<!-- end slideshow module //-->		
		<?php 	endif;	?>
		
		<?php if( $promotetop = $this->getChildHtml('promotetop') ): ?>
			<!-- sptop-container //-->
			<div id="ves-sptop-container" class="sptop-container">
				<div class="container">
					<?php echo $promotetop; ?>
				</div>	
			</div>	
			<!-- end sptop-container //-->							
		<?php 	endif;	?>
		
		
        <div id="ves-col1-layout" class="main-container col1-layout">
            <div id="ves-main" class="container">			
                <?php echo $this->getChildHtml('breadcrumbs') ?>
				<div id="current-content clearfix">	
					<div id="ves-col-main" class="col-main">
						<!-- main content -->					
						<?php echo $this->getChildHtml('global_messages') ?>
						<?php echo $this->getChildHtml('content') ?>
						<!-- end main content -->
					</div>	
				</div>
				
			<?php if( $promotebottom = $this->getChildHtml('promotebottom') ): ?>
				<!-- content bottom //-->
					<div class="spbottom-container promotebottom" >
						<div class="wrap-spbottom">
							<div class="container clr footer-links">
								<?php echo $promotebottom; ?>					
							</div>
						</div>
					</div>	
				<!-- end content bottom //-->					
			<?php 	endif;	?>
				
            </div>		
        </div>
		
        <?php echo $this->getChildHtml('footer') ?>
        <?php echo $this->getChildHtml('before_body_end') ?>
    </div>
</div>
<?php echo $this->getAbsoluteFooter() ?>
</body>
</html>
