<?php
	$name = isset($config["name"])?$config["name"]:"";
	$randid = rand();
	$mainWidth = isset($config['moduleWidth']) ? $config['moduleWidth'] : 640;
	$mainHeight = isset($config['moduleHeight']) ? $config['moduleHeight'] : 300;	
	
	$interval = isset($config['interval']) ? $config['interval'] : 3000;
	$effect = isset($config['animation']) ? $config['animation'] : 'easeInOutExpo';
	$duration = isset($config['duration']) ? $config['duration'] : 1000;
	$startItem = isset($config['startItem']) ? $config['startItem'] : 0;
	$autoplay = isset($config['autoplay']) ? $config['autoplay'] : 0;
	$maxItemDisplay = isset($config['showItem']) ? $config['showItem'] : 3;
	$navPosition = isset($config['navigationAlignment']) ? $config['navigationAlignment'] : '0';

	$navigatorHeight = (int)(isset($config['navItemHeight']) ? $config['navItemHeight'] : 30) + (int)(isset($config['thumbnail_padding_x']) ? $config['thumbnail_padding_x'] : 6);
	$navigatorWidth = (int)(isset($config['navItemWidth']) ? $config['navItemWidth'] : 30) + (int)(isset($config['thumbnail_padding_x']) ? $config['thumbnail_padding_x'] : 6);
	
	$thumbnail_width = isset($config['thumbnail_width']) ? $config['thumbnail_width'] : 85;
	$thumbnail_height = isset($config['thumbnail_height']) ? $config['thumbnail_height'] : 35;
	
	$thumbnailMargin = isset($config['thumbnail_margin']) ? $config['thumbnail_margin'] : '5px';
	$moduleHeight = isset($config['moduleHeight']) ? $config['moduleHeight'] : '300';
	$moduleWidth = isset($config['moduleWidth']) ? $config['moduleWidth'] : '640';
	$thumbnail = isset($config['thumbnail']) ? $config['thumbnail'] : 1;

?>
<?php if($list->count()>0){?>	
<?php $randid = rand(); ?>
<script type="text/javascript">
jQuery.noConflict();
jQuery(document).ready( function(){	
	var buttons = { previous:jQuery('#lofslidecontent<?php echo $randid; ?> .lof-previous') ,
					next:jQuery('#lofslidecontent<?php echo $randid; ?> .lof-next') };		
	$obj = jQuery('#lofslidecontent<?php echo $randid; ?>').lofJSidernews( { interval : <?php echo $interval  ?>,
											direction		: 'blank',	
										 	easing			: '<?php echo $effect ?>',
											duration		: <?php echo $duration ?>,
											startItem		: <?php echo $startItem ?>,
											auto			: <?php echo $autoplay ?>,
											maxItemDisplay  : <?php echo $maxItemDisplay ?>,
											navPosition     : '<?php echo $navPosition ?>',
											navigatorHeight : <?php echo $navigatorHeight ?>,
											navigatorWidth  : <?php echo $navigatorWidth ?>,
											mainWidth		: <?php echo $mainWidth ?>,
											mainHeight		: <?php echo $mainHeight ?>,													
											buttons			: buttons} );	
											
});
</script>
<?php }?>
<?php if($config['title']){?><h2><?php echo $config['title']; ?></h2><?php } ?>
<div style="height: <?php echo $moduleHeight; ?>px; width: <?php echo $moduleWidth; ?>px;" class="lof-slider-noshadown" id="lofslidecontent<?php echo $randid; ?>">
  <div class="lof-wrapper">
		<!--<div class="preload" style="display: none;"><div></div></div>-->
		<div style="height: <?php echo $mainHeight ?>px; width: <?php echo $mainWidth ?>px;" class="lof-main-outer">	
			<div class="lof-main-wapper"> 		  		
					<?php foreach ($items as $item): ?>		
						<div style="height:<?php echo $mainHeight;?>px;width:<?php echo $mainWidth;?>px;" class="lof-item">
						<img src="<?php echo $item['mainImage'];?>" alt="<?php echo str_replace('"','',$item['title']); ?>"/>								   
						  <?php if($config['showdesc']): ?>						  
							  <div class="lof-description">
								  <h3><a href="<?php echo $item['link']; ?>"><?php echo $item['title']; ?></a></h3>
								  <?php echo $item['description']; ?>
								  <?php if ($config['showdesc']=='desc-readmore'){?><a class="readon" href="<?php echo $item['link']; ?>" title=""><span><?php echo $config['readmoretext'];?></span></a><?php }?>
							  </div>										
						  <?php endif; ?>
						
						</div> 
					<?php endforeach; ?>				
			</div>    	
		</div>
		<!-- END MAIN CONTENT --> 
		
		<?php if($navPosition) : ?>
		<?php if ($config['control']): ?>
			<div class="lof-buttons-control lof-<?php echo $navPosition;?>">      	 
				<div class="lof-previous" onclick="return false" style="width: <?php echo $navigatorWidth; ?>px;">Previous</div>
				<div class="lof-next" onclick="return false" style="width: <?php echo $navigatorWidth; ?>px;">Next</div>		
			</div>				
		<?php endif; ?>	
			
		<?php if($thumbnail == 1) { ?>
			<div class="lof-navigator-wapper lof-<?php echo $navPosition; ?>">				
				<div class="lof-navigator-outer"> 
					<ul class="lof-navigator">
						<?php foreach ($items as $item): ?>								
							<li>
								<img src="<?php echo $item['thumbnail'];?>" alt="<?php echo $item['title']; ?>" />									   
							</li>
						<?php endforeach; ?>	
					</ul>
				</div>
			</div>
		<?php } ?>	
			
		<?php endif; ?> 
	</div>
</div>

